name: Risco HA MQTT Bridge
version: "1.2.5"
slug: risco-ha-mqtt-bridge
description: Bridge a Risco alarm panel to Home Assistant via MQTT using the Risco REST API
url: "https://github.com/blured/risco-ha-mqtt-bridge"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
options:
  username: ""
  password: ""
  pin: ""
  language_id: "en"
  mqtt_url: ""
  mqtt_username: ""
  mqtt_password: ""
  discovery_prefix: "homeassistant"
  interval_polling: 5000
schema:
  username: str
  password: password
  pin: password
  language_id: str
  mqtt_url: str
  mqtt_username: str?
  mqtt_password: password?
  discovery_prefix: str
  interval_polling: int
